name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.14"]
    env:
      DJANGO_SETTINGS_MODULE: mainProject.settings.dev
      # dummy django key
      DJANGO_KEY: "*5uh+tjqin)b=t_qz1_8ak2q00@o2x3z14gw@kj5lr*-b@(500"
      DB_NAME: dummyDatabase
      DB_USER: admin
      DB_PASSWORD: admin
      DB_HOST: localhost
      DB_PORT: "5432"
      EMAIL_HOST: localhost
      EMAIL_HOST_USER: ""
      EMAIL_HOST_PASSWORD: ""
      DEFAULT_FROM_EMAIL: noreply@example.com

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Ensure Docker & Compose
        run: |
          docker --version
          docker compose version || sudo apt-get update && sudo apt-get install -y docker-compose-plugin
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Docker services (postgres, redis, mail)
        run: |
          python manage.py startdockerservers
      
      - name: Wait for Containers to be ready
        run: |
          for i in {1..30}; do
            pg_isready -h localhost -p 5432 -U admin -d dummyDatabase && break
            sleep 1
          done

      - name: Apply migrations
        run: |
          python manage.py migrate

      - name: Run tests
        run: |
          python manage.py test

